version: '3'
services:
  do_you_know_fsb:
    build: ./
    ports:
      - "2011:2011"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command:
      - /start.sh
    restart: always